CC=i686-elf-gcc
CA=i686-elf-as
FLAGS=-std=gnu99 -ffreestanding -O2 -Wall -Wextra

kernel:
	$(CC) -c src/kernel.c -o bin/kernel.o $(FLAGS)

boot:
	$(CC) -c src/boot.s -o bin/boot.o

all: kernel boot

build:
	$(CC) -T src/linker.ld -o bin/myos.bin bin/kernel.o bin/boot.o